language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
before_install:
  - gem install bundler -v 1.17.3 --without guard
  - bundle _1.17.3_ install
script: bundle exec rake
services:
  - redis-server
  - mongodb
  - memcached
env:
  - RAILS_VERSION=6.0.0 SQLITE3_VERSION=1.4.1
  - RAILS_VERSION=5.2.3 SQLITE3_VERSION=1.3.11
  - RAILS_VERSION=5.1.4 SQLITE3_VERSION=1.3.11
  - RAILS_VERSION=5.0.0 SQLITE3_VERSION=1.3.11
  - RAILS_VERSION=4.2.5 SQLITE3_VERSION=1.3.11
