language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
before_install:
  - gem install bundler -v 1.17.3 --without guard
  - bundle _1.17.3_ install
script: bundle exec rubocop -D && bundle exec rake
services:
  - redis-server
  - mongodb
  - memcached
env:
  - RAILS_VERSION=6.0.0 SQLITE3_VERSION=1.4.1
  - RAILS_VERSION=5.2.3 SQLITE3_VERSION=1.3.11
  - RAILS_VERSION=5.1.4 SQLITE3_VERSION=1.3.11
  - RAILS_VERSION=5.0.0 SQLITE3_VERSION=1.3.11
  - RAILS_VERSION=4.2.5 SQLITE3_VERSION=1.3.11
  - RAILS_VERSION=3.2.21 SQLITE3_VERSION=1.3.11
matrix:
  # don't run rails 5 on ruby versions that can't install rack 2
  exclude:
    - rvm: 2.1
      env: RAILS_VERSION=5.0.0 SQLITE3_VERSION=1.3.11
    - rvm: 2.1
      env: RAILS_VERSION=5.1.4 SQLITE3_VERSION=1.3.11
    - rvm: 2.1
      env: RAILS_VERSION=5.2.3 SQLITE3_VERSION=1.3.11
    - rvm: 2.1
      env: RAILS_VERSION=6.0.0 SQLITE3_VERSION=1.4.1
    - rvm: 2.2
      env: RAILS_VERSION=6.0.0 SQLITE3_VERSION=1.4.1
    - rvm: 2.3
      env: RAILS_VERSION=6.0.0 SQLITE3_VERSION=1.4.1
    - rvm: 2.4
      env: RAILS_VERSION=6.0.0 SQLITE3_VERSION=1.4.1
